In [1]:
import numpy as np

In [37]:
a = np.arange(3*3).reshape((3, 3))

In [38]:
d = np.arange(4)

In [39]:
c = np.einsum('ij,k->kij', a, d)

In [40]:
print(a)
print(d)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3]
[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 0  2  4]
  [ 6  8 10]
  [12 14 16]]

 [[ 0  3  6]
  [ 9 12 15]
  [18 21 24]]]
